### ISSUE TITLE
grepcounter doesn't emit new messages

### ISSUE THREAD

**Issue by mateusz-blaszkowski** [sonots/fluent-plugin-grepcounter#20]
I've got the following fluentd configuration:

```
  <source>
    type tail
    path /var/log/test.log
    pos_file fluentd-docker.pos
    time_format %Y-%m-%dT%H:%M:%S
    tag test.*
    format json
    read_from_head true
  </source>
  <match **>
    @type grepcounter
    count_interval 60
    input_key validkey
    regexp validvalue
    greater_equal 1
    add_tag_prefix tagprefix
  </match>
  <match **>
    @type stdout
  </match>

```
I'd expect that after inserting the following message: 
`echo '{"validkey": "validvalue"}' >> /var/log/test.log`
into `test.log` file, the message is displayed in fluentd logs. However, it doesn't happen. When I remove grepcounter section, the message is correctly displayed.

Please correct me if I'm wrong - shouldn't it work in a way that grepcounter catches the message and emits a new message which is later caught by stdout?

Additional info:
```
# /opt/td-agent/embedded/bin/ruby --version
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]

# /opt/td-agent/embedded/bin/gem list | grep fluent-plugin-grepcounter
fluent-plugin-grepcounter (0.6.0)
```
I've also tried with v0.5.0 - issue is the same.

**Comment by sonots** [comment]
Your config is wrong. Your config absorbs all messages with the first match ** section.

Fix as:

```
  <source>
    type tail
    path /var/log/test.log
    pos_file fluentd-docker.pos
    time_format %Y-%m-%dT%H:%M:%S
    tag test.*
    format json
    read_from_head true
  </source>
  <match test.**>
    @type grepcounter
    count_interval 60
    input_key validkey
    regexp validvalue
    greater_equal 1
    add_tag_prefix tagprefix
  </match>
  <match tagprefix.**>
    @type stdout
  </match>
```

**Comment by mateusz-blaszkowski** [comment]
You're absolutely right. Thanks!
